### ISSUE TITLE
Need to explicitly set AWS_REGION even when running on aws

### ISSUE THREAD

**Issue by keis** [remind101/ssm-env#13]
This should be discovered through the service metadata instead

**Comment by ejholmes** [comment]
I think I'd disagree with this. This just uses the standard AWS SDK behavior, and for whatever reasons, the AWS SDK's don't do this by default, but I don't think tools should stray from standard AWS SDK behavior.

https://github.com/aws/aws-sdk-go/issues/1103 seems relevant

**Comment by keis** [comment]
As a counter point most other aws tools, including the awscli, does this. The golangsdk seems to be the odd one out here

**Comment by russellballestrini** [comment]
@keis I think I agree with you on this one. This has caused us trouble internally at Remind. Additionally, we would eventually like to move to multi region, having this tool automatically determine the local region by default and while still allowing an override using `AWS_REGION` seems like a more intuitive and expected behavior.
