### ISSUE TITLE
Add support for AWS Secrets Manager?

### ISSUE THREAD

**Issue by ejholmes** [remind101/ssm-env#16]
I dun screwed up with the name of this project. AWS Secrets Manager is not backed by SSM (for reasons I don't know), so you can't use the `ssm:GetParameters` API.

Should `ssm-env` support secrets in AWS Secrets Manager? Or maybe we fork this with a new name, and support both SSM/AWSSM?

I'm thinking `awssm://` (AWS Secrets Manager = AWS SM = awssm) as the scheme.

**Comment by russellballestrini** [comment]
Naming things is hard, I vote we hard fork as `awssm` name and deprecate ssm-env version.

**Comment by itsdalmo** [comment]
I vote `aws-env`, with the justification that it provides a seamless way of working with environment variables in AWS. The encryption/secret manager part is just the "best practice". 

Some things I'd like to see and would be willing to contribute towards:
- Support for not only one or the other, but both:
  - `ssm://` kept as is.
  - `sm://` for secret manager secrets.
  - Wild idea: `kms://` for KMS encrypted secrets.
- Making this importable as a library so that it can be used with e.g. AWS Lambda.

**Comment by ejholmes** [comment]
AWS just integrated SSM Parameter Store with Secrets Manager, so it’s now possible to obtain secrets in Secrets Manager using the SSM apis (and hence, ssm-env should just work out of the box).

**Comment by itsdalmo** [comment]
For anyone else interested, here is a link to the docs about referencing Secrets Manager from SSM:
https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html

I.e., to use it you need to add a prefix to any secret that is supposed to be fetched from Secrets Manager: `/aws/reference/secretsmanager/`. 

I'm surprised they did this, considering that SSM is free and has rate limits, whereas Secrets Manager is paid per secret and per 10k requests - figured any integration would be the other way around. Oh well 🤷‍♂️
